name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        spec:
          - { os: ubuntu-22.04, platform: linux, arch: x64 }
          - { os: ubuntu-22.04, platform: linux, arch: aarch64 }
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-build nix -A fossbeamer
      # These are cross-builds if executed on x64, native builds on aarch64
      - run: nix-build nix -A machine.toplevel
      - run: nix-build nix -A machine.sdImage
